### ISSUE TITLE
No esta Dalas 

### ISSUE THREAD

**Issue by DAW2Anush2** [MarthaZFQ/Validacio-MarthaZFQ#4]
Añade a nuestro salvador y para nada (guiño guiño) machista heroe

**Comment by MarthaZFQ** [comment]
Que como te quedas? uoh uoh uoh

**Comment by DAW2Anush2** [comment]
No tengo permisos

**Comment by DAW2Anush2** [comment]
Martha = Albert Primo de Rivera

**Comment by DAW2Anush2** [comment]
Martha = Albert Primo de RIvera + Rajoy fusionados

**Comment by DAW2Anush2** [comment]
Martha es peor que Dalas y ella misma lo ha adminitdo

**Comment by NuriaGA** [comment]
xD

**Comment by MarthaZFQ** [comment]
XD
